knpu_oauth2_client:
    clients:
        google:
            # must be "google" _ it activates that type!
            type: google
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
            # the route name you'll create
            redirect_route: http://127.0.0.1:8000
            redirect_params: { }
         # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"